store:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: bookstore
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY}
    access-key-secret: ${ALIYUN_SECRET_KEY}
    bucket-name: ptu-bookstore

  redis:
    host: localhost
    port: 6379
    database: 10

  alipay:
    appid: 9021000161635489
    merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDqWdRGFw7/WIV+Qsu5JZejYF88S332Kt5T4sjXxPYRwDgtFSCQROeXiHtE+YvVvPu4zS5Lqu7ajJPWvsuXAIl12hA9UvCRtS6we/05rFVhi3u+I2QJu1oBmhUOxLu1pPirl8hsfG2qdrJFFbY8Asjp0gMenyy9UDUzfHbyqBannaoKff1tvZkhH8fBleO1nGyQnhaOEoUHzOdFuyqvpSSLLNZt6n3Vn0VAwJDxiVCkkUhXf9JD7LaJWCLrL+mylKeTqsodjS6Q7YU47KxZumZuFoNvRfaZvXPT14IRGiiKu9HJfnh23JBpROjf4i8fdYgPiYNEnCs4gDAPdOJvoSqVAgMBAAECggEADuz1thkV3XF33xjF/N7GD6O9rQtp1FnamyEghY2H1o2VhlmIH2gkD+SjZTs3ir9kkNqQjkUuvUCi0dSJBu8D0ju3ORClPcJ6XMco05mEPpgxo2SBpJUIIH39xVkGU4VUSSl7nF04Ztj0da3yU1QiE7JKfJLKuKv5F3Rf5wiJmNc0nJ8f61u7YtoVNzI8MHv8YmkGyp3UERDXm5Lc1qDljbHKywAlu9WDqdWT3QVOq5C5p989ZK70c5UiPSpfl6EDW6vPC2FoxQBwqFs5QojpapP+uZ8+/H1hoy1Cavj4LHGt56atQIAd4QYKSqdyOAdjzpDORuLzmACugQtK11pMwQKBgQD8NI1gy2i/ZIijN83D8I7o2unhoxOkcmII+4p+4aFGgQIQTcx+M5KK6yaK05nUmbzOZQS+jUP7r0X/axAyQFzmlpOxsYjg1yfZvtWJIi9xBfeY3AwnZVacJ1LrZSsIZAJRnl9qEqpVdsIgK3ADreK7LY8pAGl98r1WeqAPVTI+XQKBgQDt4IFSg+6gK+Ea5Fdu93T9XkfSEpP+tEXntZ1y63iCfvvDgDppXuA7S1gr+8NYK721ZxRUXLmWgqMEFIKJkdP3p6T5UKKH90Z88DkjmYp4kOGggmwv4VXoMwaDxGG/CYohg0f4fCeJA7BVmnUPYsFM0vmwBwkv2ewoGmzP/0EpmQKBgQC2WOi/S1J4zx9bo0VKnes1wNHJKjdRdsIa7IO+KTSJ3Uy4rQdlV7RkbJB5X3ShmmZAdBlyDIFSv+9ENQyIyLBiqAwxNcNZjTZq4OdTNzxF46KZCsBe2447aNMzDvqGHojuqisibkxpbmv9Bmr+vgJogxA2/O1I+vCaTh7b9yVUoQKBgFwzWqzbClD28Qd1XhZav/O86WWZYdellDrdgCuc7VbXVUpPl1RkO9F/wKs7qFmyipOXYp/YWO7nr7vTH02nQluJlT41bOn6hE3E5sDPsIZO0cVfCAP++UdJD8tfAOwFDI80zV6Y8NIApgZoGdte0cGvPKxn7b2oYAqjQ23TaDRxAoGAC2ARyOQjxmtYaYLHZSAwblo7pAYfd1LVCHFyvYlsKHLGmpTl6v20v4OqP7IakjELDOyx3BjC6oEou89NHDgpszhEv3PLXZ7kx0SPbBUDoVy05E6vaKal5q9dATashV71cTwfbDqr6SNiBXruECoAkmikpF2ygxqnyNwdsXdNPqE=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhrT6UnFHCFHDG3c3i+Xebvxd1SWw0ovG06hi6aDk4V0YyC75mtoufzD9vYwTt6yPFaoAeKYfPL8At8igd+RA7sYQmxxxms2bzzgLtXZ2kCC9fo4X97tONqzJ6ieUEGk3d3iMIL3Pg5CbM5fAf68UMjJcqY9Xp4Rrbhmv4YJFvUaZO2bSnWCt1mGcCY9HPRp6N3Kr+Vu6BrO2WGXbyeCJyr7OQ+dUvpDtWyRAL5rolfourkeMgX7zVO8qTwpGN9mvqFfvFBWa56dfziOfJ38WPvnF0EBsm+8q45qzI1b0l/VSGP5muy0eqHwO88p+7bd5BIFSIXsDzsmwDgxx/83H8wIDAQAB
    notifyUrl: https://h6q9j1cdjz.fy.takin.cc/api/alipay/notify
    returnUrl: https://h6q9j1cdjz.fy.takin.cc/
    signType: RSA2
    charset: UTF-8
    gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
